parameters:
  - name: runEndToEndTests
    type: boolean
    default: true
    displayName: "Run end-to-end tests"

jobs:
  - job: "Build_And_Test_Java_Library_Windows"

    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022 
      os: windows

    variables:
      ApplicationInsightAgentVersion: 3.5.2

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        checkLatest: true
      displayName: 'Install NuGet Tool'

    - pwsh: |
        Write-Host "Java_HOME: $env:JAVA_HOME"
        Get-Command mvn
      displayName: 'Check Maven is installed'

    - task: UseDotNet@2
      displayName: 'Install .NET 6'
      inputs:
        version: 6.0.x
        
    - pwsh: '& .\build.ps1'
      displayName: 'Build project with java library'

    - pwsh: |
        $currDir =  Get-Location
        $Env:Path = $Env:Path+";$currDir\Azure.Functions.Cli"
        ls $currDir\Azure.Functions.Cli
        func --version
        cd ./azure-functions-java-worker/emulatedtests
        mvn clean package `-Dmaven`.javadoc`.skip=true `-Dmaven`.test`.skip `-Dorg`.slf4j`.simpleLogger`.log`.org`.apache`.maven`.cli`.transfer`.Slf4jMavenTransferListener=warn `-B
        Copy-Item "confluent_cloud_cacert.pem" ".\target\azure-functions\azure-functions-java-emulatedtests"
      displayName: 'Package Java for E2E'
      condition: eq(${{ parameters.runEndToEndTests }}, true)

    - bash: |
        npm install -g azurite
        mkdir azurite
        azurite --silent --location azurite --debug azurite\debug.log &
      displayName: 'Install and Run Azurite'
      condition: eq(${{ parameters.runEndToEndTests }}, true)

    - task: DotNetCoreCLI@2
      retryCountOnTaskFailure: 3
      inputs:
        command: 'test'
        projects: |
          azure-functions-java-worker/emulatedtests/Azure.Functions.Java.Tests.E2E/Azure.Functions.Java.Tests.E2E/Azure.Functions.Java.Tests.E2E.csproj
      env:
        AzureWebJobsStorage: "UseDevelopmentStorage=true"
        JAVA_HOME: $(JAVA_HOME_8_X64)
      displayName: 'Build & Run tests for java 8'
      condition: eq(${{ parameters.runEndToEndTests }}, true)
    