schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - dev
  always: true

trigger:
  batch: true
  branches:
    include:
    - dev

pr:
  branches:
    include:
    - dev

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - name: codeql.language
    value: java,powershell
  - name: codeql.buildIdentifier
    value: java_library_public
  - name: codeql.excludePathPatterns
    value: '/extract,/azure-maven-archetypes,/azure-maven-plugins,/azure-functions-java-worker'

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/jobs/build.yml@self